#!/usr/bin/env node
// Convert a Standard MIDI File (e.g. a Mutopia Project engraving) into a
// falling-notes data module: [midi, startBeat, durationBeats, hand, velocity].
//
// Event times are resolved through the file's full tempo map into real
// seconds, so rubato and tempo changes survive. Pieces produced this way use
// bpm=60, making one "beat" equal one second.
//
// Usage:
//   node tools/midi2data.mjs input.mid --id bach846 --hands 1:R,2:L \
//        [--rate 1.0] [--info] > js/pieces/bach846.data.js
//
//   --info   only print track/timing info to stderr (no module output)
//   --rate   playback speed multiplier (1.1 = 10% faster)

import { readFileSync } from 'node:fs';

const args = process.argv.slice(2);
const file = args[0];
const opt = (name, dflt) => {
  const i = args.indexOf('--' + name);
  return i >= 0 ? args[i + 1] : dflt;
};
const id = opt('id', 'piece');
const rate = parseFloat(opt('rate', '1'));
const infoOnly = args.includes('--info');
const handMap = Object.fromEntries(
  opt('hands', '1:R,2:L').split(',').map((p) => p.split(':'))
);

const buf = readFileSync(file);
let pos = 0;
const read32 = () => { const v = buf.readUInt32BE(pos); pos += 4; return v; };
const read16 = () => { const v = buf.readUInt16BE(pos); pos += 2; return v; };
const read8 = () => buf[pos++];
const readVarLen = () => {
  let v = 0, b;
  do { b = read8(); v = (v << 7) | (b & 0x7f); } while (b & 0x80);
  return v;
};

if (buf.toString('ascii', 0, 4) !== 'MThd') throw new Error('not a midi file');
pos = 8;
const format = read16(), ntrks = read16(), division = read16();

const tracks = [];
const tempoEvents = [{ tick: 0, usPerQ: 500000 }];
for (let t = 0; t < ntrks; t++) {
  if (buf.toString('ascii', pos, pos + 4) !== 'MTrk') throw new Error('bad track');
  pos += 4;
  const len = read32();
  const end = pos + len;
  let tick = 0, running = 0;
  const events = [];
  while (pos < end) {
    tick += readVarLen();
    let status = buf[pos];
    if (status & 0x80) { pos++; running = status; } else { status = running; }
    const type = status & 0xf0;
    if (type === 0x90 || type === 0x80) {
      const note = read8(), vel = read8();
      events.push({ tick, on: type === 0x90 && vel > 0, note, vel });
    } else if (type === 0xa0 || type === 0xb0 || type === 0xe0) pos += 2;
    else if (type === 0xc0 || type === 0xd0) pos += 1;
    else if (status === 0xff) {
      const meta = read8(), mlen = readVarLen();
      if (meta === 0x51)
        tempoEvents.push({ tick, usPerQ: (buf[pos] << 16) | (buf[pos + 1] << 8) | buf[pos + 2] });
      pos += mlen;
    } else if (status === 0xf0 || status === 0xf7) pos += readVarLen();
    else throw new Error(`unknown status 0x${status.toString(16)} @${pos}`);
  }
  pos = end;
  tracks.push(events);
}

// tick → seconds through the tempo map
tempoEvents.sort((a, b) => a.tick - b.tick);
const segments = [];
let accS = 0;
for (let i = 0; i < tempoEvents.length; i++) {
  const cur = tempoEvents[i];
  if (i > 0) {
    const prev = segments[segments.length - 1];
    accS = prev.startS + ((cur.tick - prev.tick) / division) * (prev.usPerQ / 1e6);
  }
  segments.push({ tick: cur.tick, usPerQ: cur.usPerQ, startS: accS });
}
const tickToSec = (tick) => {
  let seg = segments[0];
  for (const s of segments) { if (s.tick <= tick) seg = s; else break; }
  return seg.startS + ((tick - seg.tick) / division) * (seg.usPerQ / 1e6);
};

// pair note-on/off into notes
const notes = [];
tracks.forEach((events, ti) => {
  const open = {};
  for (const e of events) {
    if (e.on) (open[e.note] ||= []).push(e);
    else {
      const st = (open[e.note] || []).shift();
      if (!st) continue;
      const startS = tickToSec(st.tick) / rate;
      const endS = tickToSec(e.tick) / rate;
      notes.push({
        track: ti,
        midi: e.note,
        start: Math.round(startS * 1000) / 1000,
        dur: Math.max(Math.round((endS - startS) * 1000) / 1000, 0.05),
        vel: Math.round((st.vel / 127) * 100) / 100,
      });
    }
  }
});
notes.sort((a, b) => a.start - b.start || a.midi - b.midi);
const total = Math.max(...notes.map((n) => n.start + n.dur));

console.error(
  `${file}: format=${format} division=${division} tracks=${ntrks} ` +
    `notes/track=[${tracks.map((t) => t.filter((e) => e.on).length).join(', ')}] ` +
    `tempoChanges=${tempoEvents.length - 1} length=${Math.round(total)}s`
);
if (infoOnly) process.exit(0);

const rows = notes
  .map((n) => `  [${n.midi},${n.start},${n.dur},'${handMap[n.track] ?? 'L'}',${n.vel}]`)
  .join(',\n');
console.log(`// Generated by tools/midi2data.mjs from ${file.split(/[\\/]/).pop()}
// (Mutopia Project public-domain engraving). bpm=60: one beat = one second.
export const NOTES = [
${rows}
];
export const TOTAL_BEATS = ${Math.ceil(total)};
`);
